from typing import Any

from sympy.core.basic import Basic

class Expr(Basic):
    def __neg__(self) -> Expr: ...
    def __add__(self, other: Any) -> Expr: ...
    def __radd__(self, other: Any) -> Expr: ...
    def __sub__(self, other: Any) -> Expr: ...
    def __rsub__(self, other: Any) -> Expr: ...
    def __mul__(self, other: Any) -> Expr: ...
    def __rmul__(self, other: Any) -> Expr: ...
    def __truediv__(self, other: Any) -> Expr: ...
    def __rtruediv__(self, other: Any) -> Expr: ...
    def __pow__(self, other: Any) -> Expr: ...
    def __rpow__(self, other: Any) -> Expr: ...